### ISSUE TITLE
Missing / Incorrect Instructions

### ISSUE THREAD

**Issue by JonFP** [richardschoen/howtostuff#1]
First ;let me say what a useful document this is - even though it caused me some grief.

1) The instructions for setting the root password say not to start the server. But if you do not start it the request generates a "can't find the server" error.  If you start the server first however the password change works. In case anyone gets stuck it might be good to mention that the default password is blanks (just hit <enter) - I needed that to shut the server down before I got the password change to stick.

2) The instructions for editing my.cnf fail to mention that the directives must be preceded by [mysqld]. Took me a while to dig that out of the mariadb docs.

3) Were sone of the instructions cloned from a postgres document? There is mention of the instal going into a postgres directory

It would also be useful to be warned that everything within the tool and all of the commands are "mysql" - which is a tad confusing since one just installed Mariadb. I know it is the new incarnation of mysql but ...

**Comment by richardschoen** [comment]
Thanks for the note. I will review next week.  If you have any specific content updates they would be welcome.

**Comment by richardschoen** [comment]
1.) I had some time this evening to do a little editing and testing. I re-ordered the content accordingly.
2.) Added a sample of what my my.cnf file looks like. I did not need to add a [mysqld] tag so it's odd that you needed it. Just retested and actually I found where the [mysqld] tag caused an issue. I wonder if it's from a MariaDB update from IBM. 
3.) The original doc was cloned from my Postgres document. Corrected.
4.) In regards to MariaDB using the mysql commands I'm sure how much more to clarify that other than on the example that uses the mysql command I added a qualified path to make it a little clearer. 

Let me know if you find anything else and I will re-open this.

**Comment by JonFP** [comment]
Great update Richard - thanks.  Can't think of anything else that is needed - except maybe to point out that if you take the secure localhost option (I did) that the server can only be used from PHP/Python/whatever scripts. The instructions later on about remote access for example are not applicable in that context.
