### ISSUE TITLE
missing python.h

### ISSUE THREAD

**Issue by NielsLiisberg** [richardschoen/howtostuff#2]
hello Richard. 

on some systems you need to compile regex so also:

yum install python3-devel

**Comment by richardschoen** [comment]
python3-devel is noted in the doc. Thanks.

On my IBM i system i didn't have an issue with regex. have you seen issues with it ?

**Comment by NielsLiisberg** [comment]
I had with two different partitions. 7.3 and 7.4 totally random..

tir. 15. dec. 2020 kl. 00.08 skrev Richard Schoen <notifications@github.com

**Comment by richardschoen** [comment]
Would it still be relevant if all the IBM i Python 3 yum packages were installed ?

If you can tell me the commands to build regex I can add them to the doc as a warning in case of error.

**Comment by NielsLiisberg** [comment]
Sure  - if I can remember;

Python Regex is a gcc compiled feature (AFAIR) so you yum install gcc c++
( can't remember the precise package name) + dev tools where the header is.

then

pip3 install regex

.. will compile it

Then it works

... sorry - it's a little unprecise ... I give you a shout when I have the
issue next time, and give you the precise solution

**Comment by richardschoen** [comment]
Sounds good. Thanks.

**Comment by richardschoen** [comment]
Updated install instructions so MKDocs should now build correctly.
