### ISSUE TITLE
Suggest removing !includedir line from my.cnf

### ISSUE THREAD

**Issue by alanseiden** [richardschoen/howtostuff#5]
A client's MariaDb startup failed after an upgrade to IBM i 7.4 and an IPL. MariaDB reported that it couldn't find the directory `/QOpenSys/etc/mariadb/my.cnf.d`.
![image](https://user-images.githubusercontent.com/5905791/126877582-cca311e2-99d0-49e8-ab7d-9f429ade29c7.png)

The config file `/QOpenSys/etc/mariadb/my.cnf` included this line:
`!includedir /QOpenSys/etc/mariadb/my.cnf.d`

I solved the problem by creating the my.cnf.d directory:
`mkdir /QOpenSys/etc/mariadb/my.cnf.d`
and then MariaDb was able to start.

A simpler solution would have been to remove the !includedir line from my.cnf, since they had no need for the optional my.cnf.d directory.

I suggest we add the step of deleting or commenting out the !includedir line, for people who haven't added any fles inside that directory. Otherwise, the empty my.cnf.d directory may be pruned by MariaDb updates and cause the error.

Example of commenting out the line:
`#!includedir /QOpenSys/etc/mariadb/my.cnf.d`

**Comment by alanseiden** [comment]
For those who have not taken the actions above, it is still preventing MariaDb from starting after an IPL. I think we should ask IBM to change the default setting in my.cnf.

**Comment by richardschoen** [comment]
Can you make the suggested changes and a pull request  ?

**Comment by alanseiden** [comment]
@richardschoen Sure. Here it is: https://github.com/richardschoen/howtostuff/pull/7

**Comment by richardschoen** [comment]
Merged pull request.
